# -*- coding: utf-8 -*-
"""Dados de Animes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4XRbfT_Zo_6y4wtZmTZqbn4bPUjjzBV
"""

#Importação das bibliotecas utilizadas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

#Carregamento do arquivo csv com o banco de dados para o dataframe.
df_anime = pd.read_csv('anime.csv')

#Amostragem das primeiras 10 linha do dataframe.
df_anime.head(10)

#Analize dos tipos de dados das colunas.
df_anime.dtypes

#Grafico em pizza de tipos de animes em pocentagem.
df_anime['type'].value_counts().plot.pie(title='Tipos de Animes', autopct='%1.1f%%')
plt.ylabel('Tipos')
plt.legend(
           title='Tipos de animes',
           loc='center left',
           bbox_to_anchor=(1.5, 0, 0.5, 1));

#Histrograma de quantidade de animes por rating.
plt.hist(df_anime['rating'])
plt.xlabel('Rating')
plt.ylabel('Quantidade');

#Novo dataframe com os animes com rating igual ou maior de 9.
df_melhores_animes = df_anime[df_anime['rating'] >= 9]
df_melhores_animes

#Analize dos dados referente ao raking dos animes com mínima, máxima e média.
df_melhores_animes['rating'].describe()

#Grafico em boxplot com os dados da coluna rating do dataframe melhores animes.
plt.boxplot(df_melhores_animes['rating']);

#Salva o dataframe Melhores animes em um arquivo csv.
df_melhores_animes.to_csv('Melhores_animes')

